export const GET_ACLGS_START = 'GET_ACLGS_START';
export const GET_ACLGS_SUCCEED = 'GET_ACLGS_SUCCEED';
export const GET_ACLGS_FAIL = 'GET_ACLGS_FAIL';

export const GET_MDMMS_START = 'GET_MDMMS_START';
export const GET_MDMMS_SUCCEED = 'GET_MDMMS_SUCCEED';
export const GET_MDMMS_FAIL = 'GET_MDMMS_FAIL';

export const EDIT_MDMMS_START = 'EDIT_MDMMS_START';
export const EDIT_MDMMS_SUCCEED = 'EDIT_MDMMS_SUCCEED';
export const EDIT_MDMMS_FAIL = 'EDIT_MDMMS_FAIL';

export const DELETE_MDMMS_START = 'DELETE_MDMMS_START';
export const DELETE_MDMMS_SUCCEED = 'DELETE_MDMMS_SUCCEED';
export const DELETE_MDMMS_FAIL = 'DELETE_MDMMS_FAIL';

export const ADD_MDMMS_START = 'ADD_MDMMS_START';
export const ADD_MDMMS_SUCCEED = 'ADD_MDMMS_SUCCEED';
export const ADD_MDMMS_FAIL = 'ADD_MDMMS_FAIL';
